remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme

title: Web Developer
description: As a seasoned Web Developer specializing in Cyber Security, I blend creativity and technical expertise to design, develop, and secure dynamic web applications. With more than 10 years of experience in frontend and backend technologies, I ensure robust, scalable, and secure solutions. My commitment to cyber security means the applications I develop are efficient and resilient against threats, delivering exceptional and secure web experiences.
