remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme

title: Web Developer
description: As a seasoned Web Developer with a specialized focus on Cyber Security, I blend creativity and technical expertise to design, develop, and secure dynamic web applications. With [X] years of experience, I am proficient in both frontend and backend technologies, ensuring robust and scalable solutions. My commitment to cyber security ensures that the applications I develop are not only efficient but also resilient against threats. From implementing secure coding practices to conducting comprehensive security assessments, I strive to deliver exceptional, secure web experiences.
